apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-wjym
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-wjym
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-wjym
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-wjym
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-wjym
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-nthq-tenant/appstudio/devfile-sample-python-basic-wjym@sha256:42913bf3d06709c203e724009274cde4dbbf748d84391ec1d90ba541111ebcc8
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
